services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=entriesdb
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=example